### ISSUE TITLE
share data on osf.io or figshare.com

### ISSUE THREAD

**Issue by slowkow** [battle-lab/crossmap#1]
Could I ask if you might consider sharing the large data files on a permanent repository designed for sharing large data?

When I try to access your files through Box.com, I get an error because I'm trying to download too much data (more than 15GB):
![box-error](https://user-images.githubusercontent.com/209714/48303661-c68e0600-e4da-11e8-8df8-7ca5779f68be.png)

Instead of using Box.com, I would recommend these options:

- [Open Science Framework](https://osf.io) is full-featured system for sharing data and managing open science projects. It also supports figshare, github, etc.

- [figshare](https://figshare.com/features) is a great way to share lots of large data files, or any file types that you want associated to a DOI.

Thanks for the great work! I'm looking forward to exploring your data.

**Comment by alorchhota** [comment]
We are actually uploading files to figshare. I'll update the link once the upload is completed. Thanks for reporting the issue.

**Comment by alorchhota** [comment]
Pre-computed mappability and cross-mappability files have been shared through figshare with DOI: https://doi.org/10.6084/m9.figshare.c.4297352.v2
